name: Comment on the pull request

on:
  workflow_run:
    workflows: ['Generate Pull Request Bundle Stats']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Compare sizes
        uses: typeofweb/typeofweb-bundlephobia-pr-stats-action@pkg
        with:
          pr_number: ${{github.event.workflow_run.pull_requests[0].number}}
          workflow_run_id: ${{github.event.workflow_run.id}}
        env:
          GITHUB_TOKEN: ${{secrets.TYPEOFWEB_BOT_GITHUB_TOKEN}}
          COMPRESS_BUNDLES: true
